//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_proyectoxFuzzy_dificultadjuego                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "dificultadjuego"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package CodigoFuzzy;

public class TP_proyectoxFuzzy_dificultadjuego {
 private double min = 0.0;
 private double max = 100.0;
 private double step = 11.11111111111111;
 double _ps_buscarpalabra[] = { -25.0,0.0,20.0,50.0 };
 double _pl_buscarpalabra[] = {  };
 double _ps_hacerparejas[] = { 30.0,50.0,70.0 };
 double _pl_hacerparejas[] = {  };
 double _ps_memorizarpalabra[] = { 60.0,70.0,100.0,200.0 };
 double _pl_memorizarpalabra[] = {  };
 MF_xfl_trapezoid buscarpalabra = new MF_xfl_trapezoid(min,max,step,_ps_buscarpalabra,_pl_buscarpalabra);
 MF_xfl_triangle hacerparejas = new MF_xfl_triangle(min,max,step,_ps_hacerparejas,_pl_hacerparejas);
 MF_xfl_trapezoid memorizarpalabra = new MF_xfl_trapezoid(min,max,step,_ps_memorizarpalabra,_pl_memorizarpalabra);
}


