//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_proyectoxFuzzy_numeroequivocaciones                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "numeroequivocaciones"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package CodigoFuzzy;

public class TP_proyectoxFuzzy_numeroequivocaciones {
 private double min = 0.0;
 private double max = 100.0;
 private double step = 11.11111111111111;
 double _ps_bajo[] = { -100.0,0.0,60.0 };
 double _pl_bajo[] = {  };
 double _ps_alto[] = { 30.0,100.0,200.0 };
 double _pl_alto[] = {  };
 MF_xfl_triangle bajo = new MF_xfl_triangle(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_triangle alto = new MF_xfl_triangle(min,max,step,_ps_alto,_pl_alto);
}


