//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_proyectoxFuzzy_puntaje                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "puntaje"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package CodigoFuzzy;

public class TP_proyectoxFuzzy_puntaje {
 private double min = 0.0;
 private double max = 100.0;
 private double step = 11.11111111111111;
 double _ps_bajo[] = { -50.0,0.0,50.0 };
 double _pl_bajo[] = {  };
 double _ps_normal[] = { 20.0,50.0,80.0 };
 double _pl_normal[] = {  };
 double _ps_alto[] = { 60.0,100.0,150.0 };
 double _pl_alto[] = {  };
 MF_xfl_triangle bajo = new MF_xfl_triangle(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_triangle normal = new MF_xfl_triangle(min,max,step,_ps_normal,_pl_normal);
 MF_xfl_triangle alto = new MF_xfl_triangle(min,max,step,_ps_alto,_pl_alto);
}


