/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estudiante;

import CodigoFuzzy.proyectoxFuzzy;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Servicios.Servicios;

public class Cliente extends javax.swing.JFrame {

    private proyectoxFuzzy sistema;
    private final String usuario;
    private Servicios servidor;
    private List<Imagen> imagenes;
    private final Cliente cliente;
    private Estudiante estudiante;
    private int equivocaciones;
    private int palabra1;
    private int palabra2;
    private int palabra3;
    private int palabra4;

    public Cliente(String nickName, Estudiante estudiante) {
        usuario = nickName;
        sistema = new proyectoxFuzzy();
        servidor = new Servicios();
        this.estudiante = estudiante;
        equivocaciones = 0;
        this.servidor.generarDiccionario("diccionarios/animales.txt");
        this.servidor.generarDiccionario("diccionarios/colores.txt");
        imagenes = new ArrayList<>();
        initComponents();
        palabra1 = 0;
        palabra2 = 0;
        palabra3 = 0;
        palabra4 = 0;
        cliente = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        opcion = new javax.swing.ButtonGroup();
        BuscarObjeto = new javax.swing.JFrame();
        jPanelOpc1Img2 = new javax.swing.JPanel();
        jPanelOpc1Img3 = new javax.swing.JPanel();
        jPanelOpc1Img4 = new javax.swing.JPanel();
        jRadioButton1Opc1 = new javax.swing.JRadioButton();
        jRadioButton3Opc1 = new javax.swing.JRadioButton();
        jTextFieldOpc1Msj = new javax.swing.JTextField();
        jRadioButton2Opc1 = new javax.swing.JRadioButton();
        jRadioButton4Opc1 = new javax.swing.JRadioButton();
        jPanelOpc1Img1 = new javax.swing.JPanel();
        lblPuntaje = new javax.swing.JLabel();
        jTextFieldOpc1 = new javax.swing.JTextField();
        jButtonDicc = new javax.swing.JButton();
        opcionMenu1 = new javax.swing.ButtonGroup();
        opcionAdmin = new javax.swing.ButtonGroup();
        HazPareja = new javax.swing.JFrame();
        jPanelOpc2Pal1 = new javax.swing.JPanel();
        jTextField1Opc2 = new javax.swing.JTextField();
        jPanelOpc2Img2 = new javax.swing.JPanel();
        jPanelOpc2Img3 = new javax.swing.JPanel();
        jPanelOpc2Img5 = new javax.swing.JPanel();
        jPanelOpc2Pal2 = new javax.swing.JPanel();
        jTextField2Opc2 = new javax.swing.JTextField();
        jPanelOpc2Img6 = new javax.swing.JPanel();
        jPanelOpc2Img7 = new javax.swing.JPanel();
        jPanelOpc2Img1 = new javax.swing.JPanel();
        jRadioButtonJuego2Img6 = new javax.swing.JRadioButton();
        jRadioButtonJuego2Img5 = new javax.swing.JRadioButton();
        jRadioButtonJuego2Img1 = new javax.swing.JRadioButton();
        jRadioButtonJuego2Img3 = new javax.swing.JRadioButton();
        jRadioButtonJuego2Img2 = new javax.swing.JRadioButton();
        jRadioButtonJuego2Img7 = new javax.swing.JRadioButton();
        lblPuntajeJuego2 = new javax.swing.JLabel();
        jTextFieldOpc1MsjJuego2 = new javax.swing.JTextField();
        jButtonDicc1 = new javax.swing.JButton();
        opcJuego2Col1 = new javax.swing.ButtonGroup();
        opcJuego2Col2 = new javax.swing.ButtonGroup();
        Memorizar = new javax.swing.JFrame();
        lblPuntajeJuego3 = new javax.swing.JLabel();
        jTextField3Pal2 = new javax.swing.JTextField();
        jTextField3Pal1 = new javax.swing.JTextField();
        jTextField3Pal3 = new javax.swing.JTextField();
        jTextField3Pal4 = new javax.swing.JTextField();
        jTextField3Pal5 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal1 = new javax.swing.JCheckBox();
        jTextFieldOpc1MsjJuego3 = new javax.swing.JTextField();
        jTextFieldJuego3Pal1 = new javax.swing.JTextField();
        jTextFieldJuego3Pal2 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal2 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal3 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal3 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal4 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal4 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal5 = new javax.swing.JTextField();
        jTextFieldJuego3Pal6 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal6 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal7 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal7 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal8 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal8 = new javax.swing.JCheckBox();
        jCheckBoxJuego3Pal5 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal9 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal9 = new javax.swing.JCheckBox();
        jTextFieldJuego3Pal10 = new javax.swing.JTextField();
        jCheckBoxJuego3Pal10 = new javax.swing.JCheckBox();
        jButtonDiccJuego3 = new javax.swing.JButton();
        Diccionario = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDicc = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        opcConsultaDiccionario = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BuscarObjeto.setResizable(false);
        BuscarObjeto.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                BuscarObjetoWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpc1Img2Layout = new javax.swing.GroupLayout(jPanelOpc1Img2);
        jPanelOpc1Img2.setLayout(jPanelOpc1Img2Layout);
        jPanelOpc1Img2Layout.setHorizontalGroup(
            jPanelOpc1Img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelOpc1Img2Layout.setVerticalGroup(
            jPanelOpc1Img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOpc1Img3Layout = new javax.swing.GroupLayout(jPanelOpc1Img3);
        jPanelOpc1Img3.setLayout(jPanelOpc1Img3Layout);
        jPanelOpc1Img3Layout.setHorizontalGroup(
            jPanelOpc1Img3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelOpc1Img3Layout.setVerticalGroup(
            jPanelOpc1Img3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOpc1Img4Layout = new javax.swing.GroupLayout(jPanelOpc1Img4);
        jPanelOpc1Img4.setLayout(jPanelOpc1Img4Layout);
        jPanelOpc1Img4Layout.setHorizontalGroup(
            jPanelOpc1Img4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelOpc1Img4Layout.setVerticalGroup(
            jPanelOpc1Img4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        opcionMenu1.add(jRadioButton1Opc1);
        jRadioButton1Opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1Opc1ActionPerformed(evt);
            }
        });

        opcionMenu1.add(jRadioButton3Opc1);
        jRadioButton3Opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3Opc1ActionPerformed(evt);
            }
        });

        jTextFieldOpc1Msj.setEditable(false);
        jTextFieldOpc1Msj.setText("SELECCIONA LA IMAGEN QUE CORRESPONDE");
        jTextFieldOpc1Msj.setBorder(null);

        opcionMenu1.add(jRadioButton2Opc1);
        jRadioButton2Opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2Opc1ActionPerformed(evt);
            }
        });

        opcionMenu1.add(jRadioButton4Opc1);
        jRadioButton4Opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4Opc1ActionPerformed(evt);
            }
        });

        jPanelOpc1Img1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelOpc1Img1Layout = new javax.swing.GroupLayout(jPanelOpc1Img1);
        jPanelOpc1Img1.setLayout(jPanelOpc1Img1Layout);
        jPanelOpc1Img1Layout.setHorizontalGroup(
            jPanelOpc1Img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelOpc1Img1Layout.setVerticalGroup(
            jPanelOpc1Img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblPuntaje.setText("PUNTAJE");

        jTextFieldOpc1.setText("PALABRA");
        jTextFieldOpc1.setBorder(null);

        jButtonDicc.setText("Consultar diccionario");
        jButtonDicc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarObjetoLayout = new javax.swing.GroupLayout(BuscarObjeto.getContentPane());
        BuscarObjeto.getContentPane().setLayout(BuscarObjetoLayout);
        BuscarObjetoLayout.setHorizontalGroup(
            BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDicc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarObjetoLayout.createSequentialGroup()
                        .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BuscarObjetoLayout.createSequentialGroup()
                                .addComponent(jRadioButton1Opc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelOpc1Img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(BuscarObjetoLayout.createSequentialGroup()
                                .addComponent(jRadioButton3Opc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelOpc1Img3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2Opc1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton4Opc1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelOpc1Img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOpc1Img4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))
                    .addGroup(BuscarObjetoLayout.createSequentialGroup()
                        .addComponent(jTextFieldOpc1Msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
        BuscarObjetoLayout.setVerticalGroup(
            BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(BuscarObjetoLayout.createSequentialGroup()
                            .addComponent(jRadioButton1Opc1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22))
                        .addComponent(jPanelOpc1Img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelOpc1Img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadioButton2Opc1))
                .addGap(39, 39, 39)
                .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4Opc1)
                    .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(BuscarObjetoLayout.createSequentialGroup()
                            .addComponent(jRadioButton3Opc1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPuntaje))
                        .addComponent(jPanelOpc1Img3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelOpc1Img4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(BuscarObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOpc1Msj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDicc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1Opc2.setText("Palabra");

        javax.swing.GroupLayout jPanelOpc2Pal1Layout = new javax.swing.GroupLayout(jPanelOpc2Pal1);
        jPanelOpc2Pal1.setLayout(jPanelOpc2Pal1Layout);
        jPanelOpc2Pal1Layout.setHorizontalGroup(
            jPanelOpc2Pal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpc2Pal1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1Opc2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelOpc2Pal1Layout.setVerticalGroup(
            jPanelOpc2Pal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpc2Pal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1Opc2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOpc2Img2Layout = new javax.swing.GroupLayout(jPanelOpc2Img2);
        jPanelOpc2Img2.setLayout(jPanelOpc2Img2Layout);
        jPanelOpc2Img2Layout.setHorizontalGroup(
            jPanelOpc2Img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jPanelOpc2Img2Layout.setVerticalGroup(
            jPanelOpc2Img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOpc2Img3Layout = new javax.swing.GroupLayout(jPanelOpc2Img3);
        jPanelOpc2Img3.setLayout(jPanelOpc2Img3Layout);
        jPanelOpc2Img3Layout.setHorizontalGroup(
            jPanelOpc2Img3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelOpc2Img3Layout.setVerticalGroup(
            jPanelOpc2Img3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOpc2Img5Layout = new javax.swing.GroupLayout(jPanelOpc2Img5);
        jPanelOpc2Img5.setLayout(jPanelOpc2Img5Layout);
        jPanelOpc2Img5Layout.setHorizontalGroup(
            jPanelOpc2Img5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelOpc2Img5Layout.setVerticalGroup(
            jPanelOpc2Img5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jTextField2Opc2.setText("Palabra");

        javax.swing.GroupLayout jPanelOpc2Pal2Layout = new javax.swing.GroupLayout(jPanelOpc2Pal2);
        jPanelOpc2Pal2.setLayout(jPanelOpc2Pal2Layout);
        jPanelOpc2Pal2Layout.setHorizontalGroup(
            jPanelOpc2Pal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpc2Pal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2Opc2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelOpc2Pal2Layout.setVerticalGroup(
            jPanelOpc2Pal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpc2Pal2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTextField2Opc2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOpc2Img6Layout = new javax.swing.GroupLayout(jPanelOpc2Img6);
        jPanelOpc2Img6.setLayout(jPanelOpc2Img6Layout);
        jPanelOpc2Img6Layout.setHorizontalGroup(
            jPanelOpc2Img6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelOpc2Img6Layout.setVerticalGroup(
            jPanelOpc2Img6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOpc2Img7Layout = new javax.swing.GroupLayout(jPanelOpc2Img7);
        jPanelOpc2Img7.setLayout(jPanelOpc2Img7Layout);
        jPanelOpc2Img7Layout.setHorizontalGroup(
            jPanelOpc2Img7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        jPanelOpc2Img7Layout.setVerticalGroup(
            jPanelOpc2Img7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOpc2Img1Layout = new javax.swing.GroupLayout(jPanelOpc2Img1);
        jPanelOpc2Img1.setLayout(jPanelOpc2Img1Layout);
        jPanelOpc2Img1Layout.setHorizontalGroup(
            jPanelOpc2Img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelOpc2Img1Layout.setVerticalGroup(
            jPanelOpc2Img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        opcJuego2Col1.add(jRadioButtonJuego2Img6);
        jRadioButtonJuego2Img6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuego2Img6ActionPerformed(evt);
            }
        });

        opcJuego2Col1.add(jRadioButtonJuego2Img5);
        jRadioButtonJuego2Img5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuego2Img5ActionPerformed(evt);
            }
        });

        opcJuego2Col2.add(jRadioButtonJuego2Img1);
        jRadioButtonJuego2Img1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuego2Img1ActionPerformed(evt);
            }
        });

        opcJuego2Col2.add(jRadioButtonJuego2Img3);
        jRadioButtonJuego2Img3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuego2Img3ActionPerformed(evt);
            }
        });

        opcJuego2Col2.add(jRadioButtonJuego2Img2);
        jRadioButtonJuego2Img2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuego2Img2ActionPerformed(evt);
            }
        });

        opcJuego2Col1.add(jRadioButtonJuego2Img7);
        jRadioButtonJuego2Img7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuego2Img7ActionPerformed(evt);
            }
        });

        lblPuntajeJuego2.setText("PUNTAJE");

        jTextFieldOpc1MsjJuego2.setEditable(false);
        jTextFieldOpc1MsjJuego2.setText("ENCUENTRA LAS IMAGENES QUE CORRESPONDEN A LAS DOS PALABRAS");
        jTextFieldOpc1MsjJuego2.setToolTipText("");
        jTextFieldOpc1MsjJuego2.setBorder(null);

        jButtonDicc1.setText("Consultar diccionario");
        jButtonDicc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDicc1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HazParejaLayout = new javax.swing.GroupLayout(HazPareja.getContentPane());
        HazPareja.getContentPane().setLayout(HazParejaLayout);
        HazParejaLayout.setHorizontalGroup(
            HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HazParejaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HazParejaLayout.createSequentialGroup()
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJuego2Img1)
                            .addComponent(jRadioButtonJuego2Img3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelOpc2Img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOpc2Img3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonJuego2Img2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpc2Img2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelOpc2Pal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJuego2Img5)
                            .addComponent(jRadioButtonJuego2Img6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelOpc2Img5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOpc2Img6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButtonJuego2Img7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpc2Img7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelOpc2Pal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(HazParejaLayout.createSequentialGroup()
                        .addComponent(jButtonDicc1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jTextFieldOpc1MsjJuego2)
                        .addGap(41, 41, 41))
                    .addGroup(HazParejaLayout.createSequentialGroup()
                        .addComponent(lblPuntajeJuego2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 516, Short.MAX_VALUE))))
        );
        HazParejaLayout.setVerticalGroup(
            HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HazParejaLayout.createSequentialGroup()
                .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HazParejaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJuego2Img2)
                            .addComponent(jRadioButtonJuego2Img1)
                            .addGroup(HazParejaLayout.createSequentialGroup()
                                .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelOpc2Img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelOpc2Img2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanelOpc2Pal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonJuego2Img3)
                                        .addComponent(jPanelOpc2Img3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(HazParejaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpc2Img5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelOpc2Pal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonJuego2Img5))
                        .addGap(18, 18, 18)
                        .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJuego2Img7)
                            .addComponent(jPanelOpc2Img6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelOpc2Img7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonJuego2Img6))))
                .addGap(26, 26, 26)
                .addComponent(lblPuntajeJuego2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HazParejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDicc1)
                    .addComponent(jTextFieldOpc1MsjJuego2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        Memorizar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                MemorizarWindowClosed(evt);
            }
        });

        lblPuntajeJuego3.setText("PUNTAJE");

        jCheckBoxJuego3Pal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal1ActionPerformed(evt);
            }
        });

        jTextFieldOpc1MsjJuego3.setEditable(false);
        jTextFieldOpc1MsjJuego3.setText("MEMORIZA LAS PALABRAS");
        jTextFieldOpc1MsjJuego3.setBorder(null);

        jCheckBoxJuego3Pal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal2ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal3ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal4ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal6ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal7ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal8ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal5ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal9ActionPerformed(evt);
            }
        });

        jCheckBoxJuego3Pal10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJuego3Pal10ActionPerformed(evt);
            }
        });

        jButtonDiccJuego3.setText("Consultar diccionario");
        jButtonDiccJuego3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiccJuego3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MemorizarLayout = new javax.swing.GroupLayout(Memorizar.getContentPane());
        Memorizar.getContentPane().setLayout(MemorizarLayout);
        MemorizarLayout.setHorizontalGroup(
            MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemorizarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemorizarLayout.createSequentialGroup()
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addComponent(jTextField3Pal3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jCheckBoxJuego3Pal5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldJuego3Pal5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxJuego3Pal6))
                            .addComponent(jTextField3Pal4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxJuego3Pal7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jCheckBoxJuego3Pal8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemorizarLayout.createSequentialGroup()
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addComponent(jTextField3Pal5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(230, 230, 230)
                                .addComponent(jCheckBoxJuego3Pal9))
                            .addComponent(lblPuntajeJuego3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDiccJuego3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addComponent(jTextFieldJuego3Pal9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxJuego3Pal10))
                            .addComponent(jTextFieldOpc1MsjJuego3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MemorizarLayout.createSequentialGroup()
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3Pal2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextField3Pal1))
                        .addGap(88, 88, 88)
                        .addComponent(jCheckBoxJuego3Pal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxJuego3Pal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxJuego3Pal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxJuego3Pal4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJuego3Pal4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MemorizarLayout.setVerticalGroup(
            MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemorizarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemorizarLayout.createSequentialGroup()
                        .addComponent(jTextField3Pal1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3Pal2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(MemorizarLayout.createSequentialGroup()
                            .addComponent(jCheckBoxJuego3Pal1)
                            .addGap(34, 34, 34))
                        .addComponent(jTextFieldJuego3Pal1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemorizarLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldJuego3Pal2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldJuego3Pal3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldJuego3Pal4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBoxJuego3Pal2)
                                    .addComponent(jCheckBoxJuego3Pal3)
                                    .addComponent(jCheckBoxJuego3Pal4))
                                .addGap(34, 34, 34)))))
                .addGap(18, 18, 18)
                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemorizarLayout.createSequentialGroup()
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldJuego3Pal6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJuego3Pal7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJuego3Pal8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MemorizarLayout.createSequentialGroup()
                                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxJuego3Pal6)
                                            .addComponent(jCheckBoxJuego3Pal7)
                                            .addComponent(jCheckBoxJuego3Pal8))
                                        .addGap(34, 34, 34))))
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addComponent(jTextField3Pal3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3Pal4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldJuego3Pal9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3Pal5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldJuego3Pal10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MemorizarLayout.createSequentialGroup()
                                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBoxJuego3Pal9)
                                    .addComponent(jCheckBoxJuego3Pal10))
                                .addGap(34, 34, 34))))
                    .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(MemorizarLayout.createSequentialGroup()
                            .addComponent(jCheckBoxJuego3Pal5)
                            .addGap(34, 34, 34))
                        .addComponent(jTextFieldJuego3Pal5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MemorizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemorizarLayout.createSequentialGroup()
                        .addComponent(jButtonDiccJuego3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntajeJuego3))
                    .addComponent(jTextFieldOpc1MsjJuego3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTextAreaDicc.setColumns(20);
        jTextAreaDicc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDicc);

        javax.swing.GroupLayout DiccionarioLayout = new javax.swing.GroupLayout(Diccionario.getContentPane());
        Diccionario.getContentPane().setLayout(DiccionarioLayout);
        DiccionarioLayout.setHorizontalGroup(
            DiccionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiccionarioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        DiccionarioLayout.setVerticalGroup(
            DiccionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiccionarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        opcion.add(opcConsultaDiccionario);
        opcConsultaDiccionario.setText("Consultar el diccionario");
        opcConsultaDiccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultaDiccionarioActionPerformed(evt);
            }
        });

        jButton1.setText("Iniciar Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(opcConsultaDiccionario)
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcConsultaDiccionario)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiante", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1Opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1Opc1ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc1Img1.getComponent(0));
        if (servidor.validarImagen(jTextFieldOpc1.getText(), im.getCodigo())) {
            correcto(2);
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 8;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButton1Opc1ActionPerformed

    /**
     * si el resultado de cualquier juego es correcto, se sumara una cantidad al
     * puntaje del usuario
     *
     * @param cantidad
     */
    private void correcto(int cantidad) {
        estudiante.puntos(cantidad);
        lblPuntaje.setText("PUNTAJE: " + estudiante.puntos());
        jTextFieldOpc1Msj.setText("Muy bien " + usuario + " :)");
    }

    private void correctoJuego2(int cantidad) {
        estudiante.puntos(cantidad);
        lblPuntajeJuego2.setText("PUNTAJE: " + estudiante.puntos());
        jTextFieldOpc1MsjJuego2.setText("Muy bien " + usuario + " :)");
    }

    private void correctoJuego3(int cantidad) {
        estudiante.puntos(cantidad);
        lblPuntajeJuego3.setText("PUNTAJE: " + estudiante.puntos());
        jTextFieldOpc1MsjJuego3.setText("Muy bien " + usuario + " :)");
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * crea una nueva ronda de 4 imagenes para el juego buscar palabra.
     */
    private void crearRonda() {
        limpiar();
        opcionMenu1.clearSelection();
        cargarImagenes(4);
        Imagen im1 = imagenes.get(0);
        jPanelOpc1Img1.add(im1);
        im1.paint(jPanelOpc1Img1.getGraphics());
        Imagen im2 = imagenes.get(1);
        jPanelOpc1Img2.add(im2);
        im1.paint(jPanelOpc1Img2.getGraphics());
        Imagen im3 = imagenes.get(2);
        jPanelOpc1Img3.add(im3);
        im1.paint(jPanelOpc1Img3.getGraphics());
        Imagen im4 = imagenes.get(3);
        jPanelOpc1Img4.add(im4);
        im1.paint(jPanelOpc1Img4.getGraphics());
        int seleccionado = (int) ((Math.random() * 100) % 4);
        String palabra = servidor.getPalabra(imagenes.get(seleccionado).getCodigo());
        String[] aux = palabra.split(";");
        jTextFieldOpc1.setText(aux[1]);
        jTextAreaDicc.setText(aux[1] + ": " + aux[2]);
        palabra1 = aux[1].length();
    }

    private void crearRondaOpc2() {
        limpiarOpc2();
        img1OK = false;
        img2OK = false;
        jTextFieldOpc1MsjJuego2.setText("SELECCIONA LA IMAGEN QUE CORRESPONDE");
        opcJuego2Col1.clearSelection();
        opcJuego2Col2.clearSelection();
        cargarImagenes(6);
        Imagen im1 = imagenes.get(0);
        jPanelOpc2Img1.add(im1);
        im1.paint(jPanelOpc2Img1.getGraphics());
        Imagen im2 = imagenes.get(1);
        jPanelOpc2Img2.add(im2);
        im1.paint(jPanelOpc2Img2.getGraphics());
        Imagen im3 = imagenes.get(2);
        jPanelOpc2Img3.add(im3);
        im1.paint(jPanelOpc2Img3.getGraphics());
        Imagen im4 = imagenes.get(3);
        jPanelOpc2Img5.add(im4);
        im1.paint(jPanelOpc2Img5.getGraphics());
        Imagen im5 = imagenes.get(4);
        jPanelOpc2Img6.add(im5);
        im1.paint(jPanelOpc2Img6.getGraphics());
        Imagen im6 = imagenes.get(5);
        jPanelOpc2Img7.add(im6);
        im1.paint(jPanelOpc2Img7.getGraphics());
        int seleccionado1 = (int) ((Math.random() * (5 - 4 + 1) + 4));
        int seleccionado2 = (int) ((Math.random() * 100) % 3);
        jTextField1Opc2.setText(servidor.getPalabra(imagenes.get(seleccionado1).getCodigo()).split(";")[1]);
        jTextField2Opc2.setText(servidor.getPalabra(imagenes.get(seleccionado2).getCodigo()).split(";")[1]);
        String traducir = servidor.getPalabra(imagenes.get(seleccionado1).getCodigo()).split(";")[2];
        String traducir2 = servidor.getPalabra(imagenes.get(seleccionado2).getCodigo()).split(";")[2];
        jTextAreaDicc.setText(jTextField1Opc2.getText() + ": " + traducir + "\n" + jTextField2Opc2.getText() + ": " + traducir2);
        palabra1 = servidor.getPalabra(imagenes.get(seleccionado1).getCodigo()).split(";")[1].length();
        palabra2 = servidor.getPalabra(imagenes.get(seleccionado2).getCodigo()).split(";")[1].length();
    }

    private void crearRondaOpc3(int cantPal) {
        limpiarOpc3();
        validar1 = false;
        validar2 = false;
        validar3 = false;
        validar4 = false;
        validar5 = false;
        cargarImagenes(11);
        int pal1 = (int) ((Math.random() * 100) % 8);
        int pal2 = (int) ((Math.random() * 100) % 8);
        while (pal2 == pal1) {
            pal2 = (int) ((Math.random() * 100) % 8);
        }
        int pal3 = (int) ((Math.random() * 100) % 8);
        while (pal3 == pal1 || pal3 == pal2) {
            pal3 = (int) ((Math.random() * 100) % 8);
        }
        int pal4 = (int) ((Math.random() * 100) % 8);
        while (pal4 == pal1 || pal4 == pal2 || pal4 == pal3) {
            pal4 = (int) ((Math.random() * 100) % 8);
        }
        jTextField3Pal1.setText(servidor.getPalabra(imagenes.get(pal1).getCodigo()).split(";")[1]);
        jTextField3Pal2.setText(servidor.getPalabra(imagenes.get(pal2).getCodigo()).split(";")[1]);
        jTextField3Pal3.setText(servidor.getPalabra(imagenes.get(pal3).getCodigo()).split(";")[1]);
        jTextField3Pal4.setText(servidor.getPalabra(imagenes.get(pal4).getCodigo()).split(";")[1]);
        jTextField3Pal5.setVisible(false);
        jTextFieldJuego3Pal1.setText(servidor.getPalabra(imagenes.get(pal3).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal2.setText(servidor.getPalabra(imagenes.get((int) ((Math.random() * 100) % 10)).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal3.setText(servidor.getPalabra(imagenes.get(pal4).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal4.setText(servidor.getPalabra(imagenes.get((int) ((Math.random() * 100) % 10)).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal5.setText(servidor.getPalabra(imagenes.get((int) ((Math.random() * 100) % 10)).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal6.setText(servidor.getPalabra(imagenes.get(pal1).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal7.setText(servidor.getPalabra(imagenes.get((int) ((Math.random() * 100) % 10)).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal8.setText(servidor.getPalabra(imagenes.get(pal2).getCodigo()).split(";")[1]);
        jTextFieldJuego3Pal7.setVisible(true);
        jTextFieldJuego3Pal8.setVisible(true);
        jCheckBoxJuego3Pal7.setVisible(true);
        jCheckBoxJuego3Pal8.setVisible(true);
        String traducir1 = servidor.getPalabra(imagenes.get(pal1).getCodigo()).split(";")[2];
        String traducir2 = servidor.getPalabra(imagenes.get(pal2).getCodigo()).split(";")[2];
        String traducir3 = servidor.getPalabra(imagenes.get(pal3).getCodigo()).split(";")[2];
        String traducir4 = servidor.getPalabra(imagenes.get(pal4).getCodigo()).split(";")[2];
        jTextAreaDicc.setText(jTextField3Pal1.getText() + ": " + traducir1 + "\n" + jTextField3Pal2.getText() + ": " + traducir2
                + "\n" + jTextField3Pal3.getText() + ": " + traducir3 + "\n" + jTextField3Pal4.getText() + ": " + traducir4);
        palabra1 = servidor.getPalabra(imagenes.get(pal1).getCodigo()).split(";")[1].length();
        palabra2 = servidor.getPalabra(imagenes.get(pal2).getCodigo()).split(";")[1].length();
        palabra3 = servidor.getPalabra(imagenes.get(pal3).getCodigo()).split(";")[1].length();
        palabra4 = servidor.getPalabra(imagenes.get(pal4).getCodigo()).split(";")[1].length();
    }

    private void jRadioButton2Opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2Opc1ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc1Img2.getComponent(0));
        if (servidor.validarImagen(jTextFieldOpc1.getText(), im.getCodigo())) {
            correcto(2);
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 8;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButton2Opc1ActionPerformed

    private void jRadioButton3Opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3Opc1ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc1Img3.getComponent(0));
        if (servidor.validarImagen(jTextFieldOpc1.getText(), im.getCodigo())) {
            correcto(2);
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 8;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButton3Opc1ActionPerformed

    private void jRadioButton4Opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4Opc1ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc1Img4.getComponent(0));
        if (servidor.validarImagen(jTextFieldOpc1.getText(), im.getCodigo())) {
            correcto(2);
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 8;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButton4Opc1ActionPerformed

    private void BuscarObjetoWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_BuscarObjetoWindowClosing
        cliente.setVisible(true);
    }//GEN-LAST:event_BuscarObjetoWindowClosing
    private boolean img1OK = false;
    private boolean img2OK = false;
    private void jRadioButtonJuego2Img1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuego2Img1ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc2Img1.getComponent(0));
        if (servidor.validarImagen(jTextField2Opc2.getText(), im.getCodigo())) {
            img2OK = true;
            if (img1OK) {
                correctoJuego2(4);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 6;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButtonJuego2Img1ActionPerformed

    private void jRadioButtonJuego2Img2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuego2Img2ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc2Img2.getComponent(0));
        if (servidor.validarImagen(jTextField2Opc2.getText(), im.getCodigo())) {
            img2OK = true;
            if (img1OK) {
                correctoJuego2(4);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 6;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButtonJuego2Img2ActionPerformed

    private void jRadioButtonJuego2Img3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuego2Img3ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc2Img3.getComponent(0));
        if (servidor.validarImagen(jTextField2Opc2.getText(), im.getCodigo())) {
            img2OK = true;
            if (img1OK) {
                correctoJuego2(4);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 6;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButtonJuego2Img3ActionPerformed

    private void jRadioButtonJuego2Img5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuego2Img5ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc2Img5.getComponent(0));
        if (servidor.validarImagen(jTextField1Opc2.getText(), im.getCodigo())) {
            img1OK = true;
            if (img2OK) {
                correctoJuego2(4);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 6;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButtonJuego2Img5ActionPerformed

    private void jRadioButtonJuego2Img6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuego2Img6ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc2Img6.getComponent(0));
        if (servidor.validarImagen(jTextField1Opc2.getText(), im.getCodigo())) {
            img1OK = true;
            if (img2OK) {
                correctoJuego2(4);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 6;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButtonJuego2Img6ActionPerformed

    private void jRadioButtonJuego2Img7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuego2Img7ActionPerformed
        Imagen im = (Imagen) (this.jPanelOpc2Img7.getComponent(0));
        if (servidor.validarImagen(jTextField1Opc2.getText(), im.getCodigo())) {
            img1OK = true;
            if (img2OK) {
                correctoJuego2(4);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lo siento, perdiste");
            equivocaciones += 6;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jRadioButtonJuego2Img7ActionPerformed
    private boolean validar1 = false;
    private boolean validar2 = false;
    private boolean validar3 = false;
    private boolean validar4 = false;
    private boolean validar5 = false;
    private boolean segundaFase = true;
    private boolean terceraFase = true;

    private void jCheckBoxJuego3Pal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal1ActionPerformed
        validar();
    }//GEN-LAST:event_jCheckBoxJuego3Pal1ActionPerformed

    private void validar() {
        if (!terceraFase) {
            if (!segundaFase) {
                if (jTextFieldJuego3Pal1.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal1.getText().equals(jTextField3Pal2.getText())) {
                    if (!validar1 && !segundaFase) {
                        validar1 = true;
                    } else {
                        segundaFase = true;
                        validar1 = false;
                        validar2 = false;
                        validar3 = false;
                        validar4 = false;
                        validar5 = false;
                        correctoJuego3(6);
                    }
                } else {
                    jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                    equivocaciones += 4;
                    iniciarNuevoJuego();
                }
            } else if (segundaFase && !terceraFase && (jTextFieldJuego3Pal1.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal1.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal1.getText().equals(jTextField3Pal3.getText()))) {
                if (!validar1 && !terceraFase) {
                    validar1 = true;
                } else if (!validar2 && !terceraFase) {
                    validar2 = true;
                } else {
                    terceraFase = true;
                    validar1 = false;
                    validar2 = false;
                    validar3 = false;
                    validar4 = false;
                    validar5 = false;
                    correctoJuego3(6);
                }
            } else {
                jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                equivocaciones += 4;
                iniciarNuevoJuego();
            }
        } else if (terceraFase && (jTextFieldJuego3Pal1.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal1.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal1.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal1.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }

    private void jCheckBoxJuego3Pal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal2ActionPerformed
        if (!terceraFase) {
            if (!segundaFase) {
                if (jTextFieldJuego3Pal2.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal2.getText().equals(jTextField3Pal2.getText())) {
                    if (!validar1 && !segundaFase) {
                        validar1 = true;
                    } else {
                        segundaFase = true;
                        validar1 = false;
                        validar2 = false;
                        validar3 = false;
                        validar4 = false;
                        validar5 = false;
                        correctoJuego3(6);
                    }
                } else {
                    jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                    equivocaciones += 4;
                    iniciarNuevoJuego();
                }
            } else if (segundaFase && !terceraFase && (jTextFieldJuego3Pal2.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal2.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal2.getText().equals(jTextField3Pal3.getText()))) {
                if (!validar1 && !terceraFase) {
                    validar1 = true;
                } else if (!validar2 && !terceraFase) {
                    validar2 = true;
                } else {
                    terceraFase = true;
                    validar1 = false;
                    validar2 = false;
                    validar3 = false;
                    validar4 = false;
                    validar5 = false;
                    correctoJuego3(6);
                }
            } else {
                jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                equivocaciones += 4;
                iniciarNuevoJuego();
            }
        } else if (terceraFase && (jTextFieldJuego3Pal2.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal2.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal2.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal2.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }

    }//GEN-LAST:event_jCheckBoxJuego3Pal2ActionPerformed

    private void jCheckBoxJuego3Pal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal3ActionPerformed
        if (!terceraFase) {
            if (!segundaFase) {
                if (jTextFieldJuego3Pal3.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal3.getText().equals(jTextField3Pal2.getText())) {
                    if (!validar1 && !segundaFase) {
                        validar1 = true;
                    } else {
                        segundaFase = true;
                        validar1 = false;
                        validar2 = false;
                        validar3 = false;
                        validar4 = false;
                        validar5 = false;
                        correctoJuego3(6);

                    }
                } else {
                    jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                    equivocaciones += 4;
                    iniciarNuevoJuego();
                }
            } else if (segundaFase && !terceraFase && (jTextFieldJuego3Pal3.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal3.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal3.getText().equals(jTextField3Pal3.getText()))) {
                if (!validar1 && !terceraFase) {
                    validar1 = true;
                } else if (!validar2 && !terceraFase) {
                    validar2 = true;
                } else {
                    terceraFase = true;
                    validar1 = false;
                    validar2 = false;
                    validar3 = false;
                    validar4 = false;
                    validar5 = false;
                    correctoJuego3(6);
                }
            } else {
                jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                equivocaciones += 4;
                iniciarNuevoJuego();
            }
        } else if (terceraFase && (jTextFieldJuego3Pal3.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal3.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal3.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal3.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
                JOptionPane.showMessageDialog(null, "Felicidades, completaste todo el juego");
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jCheckBoxJuego3Pal3ActionPerformed

    private void jCheckBoxJuego3Pal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal4ActionPerformed
        if (!terceraFase) {
            if (!segundaFase) {
                if (jTextFieldJuego3Pal4.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal4.getText().equals(jTextField3Pal2.getText())) {
                    if (!validar1 && !segundaFase) {
                        validar1 = true;
                    } else {
                        segundaFase = true;
                        validar1 = false;
                        validar2 = false;
                        validar3 = false;
                        validar4 = false;
                        validar5 = false;
                        correctoJuego3(6);

                    }
                } else {
                    jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                    equivocaciones += 4;
                    iniciarNuevoJuego();
                }
            } else if (segundaFase && !terceraFase && (jTextFieldJuego3Pal4.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal4.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal4.getText().equals(jTextField3Pal3.getText()))) {
                if (!validar1 && !terceraFase) {
                    validar1 = true;
                } else if (!validar2 && !terceraFase) {
                    validar2 = true;
                } else {
                    terceraFase = true;
                    validar1 = false;
                    validar2 = false;
                    validar3 = false;
                    validar4 = false;
                    validar5 = false;
                    correctoJuego3(6);
                }
            } else {
                jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                equivocaciones += 4;
                iniciarNuevoJuego();
            }
        } else if (terceraFase && (jTextFieldJuego3Pal1.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal4.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal4.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal4.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jCheckBoxJuego3Pal4ActionPerformed

    private void jCheckBoxJuego3Pal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal6ActionPerformed
        if (!terceraFase) {
            if (segundaFase && !terceraFase && (jTextFieldJuego3Pal6.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal6.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal6.getText().equals(jTextField3Pal3.getText()))) {
                if (!validar1 && !terceraFase) {
                    validar1 = true;
                } else if (!validar2 && !terceraFase) {
                    validar2 = true;
                } else {
                    terceraFase = true;
                    validar1 = false;
                    validar2 = false;
                    validar3 = false;
                    validar4 = false;
                    validar5 = false;
                    correctoJuego3(6);
                }
            } else {
                jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                equivocaciones += 4;
                iniciarNuevoJuego();
            }
        } else if (terceraFase && (jTextFieldJuego3Pal6.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal6.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal6.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal6.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jCheckBoxJuego3Pal6ActionPerformed

    private void jCheckBoxJuego3Pal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal7ActionPerformed
        if (terceraFase && (jTextFieldJuego3Pal7.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal7.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal7.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal7.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jCheckBoxJuego3Pal7ActionPerformed

    private void jCheckBoxJuego3Pal8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal8ActionPerformed
        if (terceraFase && (jTextFieldJuego3Pal8.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal8.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal8.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal8.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jCheckBoxJuego3Pal8ActionPerformed

    private void jCheckBoxJuego3Pal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal5ActionPerformed
        if (!terceraFase) {
            if (segundaFase && !terceraFase && (jTextFieldJuego3Pal5.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal5.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal5.getText().equals(jTextField3Pal3.getText()))) {
                if (!validar1 && !terceraFase) {
                    validar1 = true;
                } else if (!validar2 && !terceraFase) {
                    validar2 = true;
                } else {
                    terceraFase = true;
                    validar1 = false;
                    validar2 = false;
                    validar3 = false;
                    validar4 = false;
                    validar5 = false;
                    correctoJuego3(6);
                }
            } else {
                jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
                equivocaciones += 4;
                iniciarNuevoJuego();
            }
        } else if (terceraFase && (jTextFieldJuego3Pal5.getText().equals(jTextField3Pal1.getText()) || jTextFieldJuego3Pal5.getText().equals(jTextField3Pal2.getText()) || jTextFieldJuego3Pal5.getText().equals(jTextField3Pal3.getText()) || jTextFieldJuego3Pal5.getText().equals(jTextField3Pal4.getText()))) {
            if (!validar1) {
                validar1 = true;
            } else if (!validar2) {
                validar2 = true;
            } else if (!validar3) {
                validar3 = true;
            } else {
                validar1 = false;
                validar2 = false;
                validar3 = false;
                validar4 = false;
                validar5 = false;
                correctoJuego3(6);
            }
        } else {
            jTextFieldOpc1MsjJuego3.setText("Upppssss :(");
            equivocaciones += 4;
            iniciarNuevoJuego();
        }
    }//GEN-LAST:event_jCheckBoxJuego3Pal5ActionPerformed

    private void jCheckBoxJuego3Pal9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxJuego3Pal9ActionPerformed

    private void jCheckBoxJuego3Pal10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuego3Pal10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxJuego3Pal10ActionPerformed

    private void jButtonDiccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiccActionPerformed
        Diccionario.setBounds(0, 0, 305, 250);
        Diccionario.setVisible(true);

    }//GEN-LAST:event_jButtonDiccActionPerformed

    private void jButtonDicc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDicc1ActionPerformed
        Diccionario.setBounds(0, 0, 305, 250);
        Diccionario.setVisible(true);
    }//GEN-LAST:event_jButtonDicc1ActionPerformed

    private void MemorizarWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_MemorizarWindowClosed
        validar1 = false;
        validar2 = false;
        validar3 = false;
        validar4 = false;
        validar5 = false;
        segundaFase = false;
        terceraFase = false;
    }//GEN-LAST:event_MemorizarWindowClosed

    private void jButtonDiccJuego3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiccJuego3ActionPerformed
        Diccionario.setBounds(0, 0, 305, 250);
        Diccionario.setVisible(true);
    }//GEN-LAST:event_jButtonDiccJuego3ActionPerformed

    private void opcConsultaDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultaDiccionarioActionPerformed
        String palabra = JOptionPane.showInputDialog("Ingresa la palabra a buscar");
        if (palabra != null && !palabra.isEmpty()) {
            String traduccion = servidor.buscarPalabra(palabra);
            if (traduccion != null && !traduccion.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, palabra + ": " + traduccion, "Traducción", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "La palabra: " + palabra + " no se encuentra en los diccionarios.", "Traducción", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_opcConsultaDiccionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        estudiante.setCliente(cliente);
        iniciarNuevoJuego();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame BuscarObjeto;
    private javax.swing.JFrame Diccionario;
    private javax.swing.JFrame HazPareja;
    private javax.swing.JFrame Memorizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDicc;
    private javax.swing.JButton jButtonDicc1;
    private javax.swing.JButton jButtonDiccJuego3;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal1;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal10;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal2;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal3;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal4;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal5;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal6;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal7;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal8;
    private javax.swing.JCheckBox jCheckBoxJuego3Pal9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelOpc1Img1;
    private javax.swing.JPanel jPanelOpc1Img2;
    private javax.swing.JPanel jPanelOpc1Img3;
    private javax.swing.JPanel jPanelOpc1Img4;
    private javax.swing.JPanel jPanelOpc2Img1;
    private javax.swing.JPanel jPanelOpc2Img2;
    private javax.swing.JPanel jPanelOpc2Img3;
    private javax.swing.JPanel jPanelOpc2Img5;
    private javax.swing.JPanel jPanelOpc2Img6;
    private javax.swing.JPanel jPanelOpc2Img7;
    private javax.swing.JPanel jPanelOpc2Pal1;
    private javax.swing.JPanel jPanelOpc2Pal2;
    private javax.swing.JRadioButton jRadioButton1Opc1;
    private javax.swing.JRadioButton jRadioButton2Opc1;
    private javax.swing.JRadioButton jRadioButton3Opc1;
    private javax.swing.JRadioButton jRadioButton4Opc1;
    private javax.swing.JRadioButton jRadioButtonJuego2Img1;
    private javax.swing.JRadioButton jRadioButtonJuego2Img2;
    private javax.swing.JRadioButton jRadioButtonJuego2Img3;
    private javax.swing.JRadioButton jRadioButtonJuego2Img5;
    private javax.swing.JRadioButton jRadioButtonJuego2Img6;
    private javax.swing.JRadioButton jRadioButtonJuego2Img7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDicc;
    private javax.swing.JTextField jTextField1Opc2;
    private javax.swing.JTextField jTextField2Opc2;
    private javax.swing.JTextField jTextField3Pal1;
    private javax.swing.JTextField jTextField3Pal2;
    private javax.swing.JTextField jTextField3Pal3;
    private javax.swing.JTextField jTextField3Pal4;
    private javax.swing.JTextField jTextField3Pal5;
    private javax.swing.JTextField jTextFieldJuego3Pal1;
    private javax.swing.JTextField jTextFieldJuego3Pal10;
    private javax.swing.JTextField jTextFieldJuego3Pal2;
    private javax.swing.JTextField jTextFieldJuego3Pal3;
    private javax.swing.JTextField jTextFieldJuego3Pal4;
    private javax.swing.JTextField jTextFieldJuego3Pal5;
    private javax.swing.JTextField jTextFieldJuego3Pal6;
    private javax.swing.JTextField jTextFieldJuego3Pal7;
    private javax.swing.JTextField jTextFieldJuego3Pal8;
    private javax.swing.JTextField jTextFieldJuego3Pal9;
    private javax.swing.JTextField jTextFieldOpc1;
    private javax.swing.JTextField jTextFieldOpc1Msj;
    private javax.swing.JTextField jTextFieldOpc1MsjJuego2;
    private javax.swing.JTextField jTextFieldOpc1MsjJuego3;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntajeJuego2;
    private javax.swing.JLabel lblPuntajeJuego3;
    private javax.swing.JRadioButton opcConsultaDiccionario;
    private javax.swing.ButtonGroup opcJuego2Col1;
    private javax.swing.ButtonGroup opcJuego2Col2;
    private javax.swing.ButtonGroup opcion;
    private javax.swing.ButtonGroup opcionAdmin;
    private javax.swing.ButtonGroup opcionMenu1;
    // End of variables declaration//GEN-END:variables

    /**
     * Carga cierta cantidad de imagenes de manera aleatoria en la lista de
     * imagenes
     *
     * @param cantidad
     */
    private void cargarImagenes(int cantidad) {
        int i = 0;
        imagenes = new ArrayList<>();
        while (i < cantidad) {
            String palabra = servidor.getPalabraAletoria();
            if (!palabra.isEmpty()) {
                String[] aux = palabra.split(";");
                int codigo = Integer.parseInt(aux[0]);
                if (!existeImagen(codigo)) {
                    imagenes.add(new Imagen("imagenes/" + aux[1] + ".jpg", codigo));
                    i++;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error!! no hay palabras en los diccionarios");
                break;
            }
        }
    }

    /**
     * Valida si una imagen ya existe en la lista de imagenes
     *
     * @param codigo a ser buscado en la lista de imagenes
     * @return true si el codigo ingresado coincide con alguno de la lista de
     * imagenes, false en caso de no encontrarlo
     */
    private boolean existeImagen(int codigo) {
        boolean existe = false;
        for (Imagen i : imagenes) {
            if (!existe) {
                if (i.getCodigo() == codigo) {
                    existe = true;
                }
            } else {
                break;
            }
        }
        return existe;
    }

    private void limpiar() {
        try {
            imagenes = null;
            jPanelOpc1Img1.removeAll();
            jPanelOpc1Img1.repaint();
            jPanelOpc1Img2.removeAll();
            jPanelOpc1Img2.repaint();
            jPanelOpc1Img3.removeAll();
            jPanelOpc1Img3.repaint();
            jPanelOpc1Img4.removeAll();
            jPanelOpc1Img4.repaint();
        } catch (Exception e) {
        }
    }

    private void limpiarOpc2() {
        try {
            imagenes = null;
            jPanelOpc2Img1.removeAll();
            jPanelOpc2Img1.repaint();
            jPanelOpc2Img2.removeAll();
            jPanelOpc2Img2.repaint();
            jPanelOpc2Img3.removeAll();
            jPanelOpc2Img3.repaint();
            jPanelOpc2Img5.removeAll();
            jPanelOpc2Img5.repaint();
            jPanelOpc2Img6.removeAll();
            jPanelOpc2Img6.repaint();
            jPanelOpc2Img7.removeAll();
            jPanelOpc2Img7.repaint();
        } catch (Exception e) {
        }
    }

    private void limpiarOpc3() {
        try {
            jCheckBoxJuego3Pal1.setSelected(false);
            jCheckBoxJuego3Pal2.setSelected(false);
            jCheckBoxJuego3Pal3.setSelected(false);
            jCheckBoxJuego3Pal4.setSelected(false);
            jCheckBoxJuego3Pal5.setSelected(false);
            jCheckBoxJuego3Pal6.setSelected(false);
            jCheckBoxJuego3Pal7.setSelected(false);
            jCheckBoxJuego3Pal8.setSelected(false);
            jCheckBoxJuego3Pal9.setSelected(false);
            jCheckBoxJuego3Pal10.setSelected(false);

            jTextFieldJuego3Pal1.removeAll();
            jTextFieldJuego3Pal2.removeAll();
            jTextFieldJuego3Pal3.removeAll();
            jTextFieldJuego3Pal4.removeAll();
            jTextFieldJuego3Pal5.removeAll();
            jTextFieldJuego3Pal6.removeAll();
            jTextFieldJuego3Pal7.removeAll();
            jTextFieldJuego3Pal8.removeAll();
            jTextFieldJuego3Pal9.removeAll();
            jTextFieldJuego3Pal10.removeAll();
        } catch (Exception e) {
        }
    }

    private void visiblePalabra(boolean visible) {
        jTextField3Pal1.setVisible(visible);
        jTextField3Pal2.setVisible(visible);
        jTextField3Pal3.setVisible(visible);
        jTextField3Pal4.setVisible(visible);
        jTextField3Pal5.setVisible(false);
    }

    private int jugar(double[] data) {
        double dificultad = data[0];
        if (dificultad >= 0 && dificultad < 35) {
            return 1;
        } else {
            if (dificultad >= 35 && dificultad < 60) {
                return 2;
            } else {
                return 3;
            }
        }
    }

    public void iniciarNuevoJuego() {
        BuscarObjeto.setVisible(false);
        HazPareja.setVisible(false);
        Memorizar.setVisible(false);
        double[] _input = new double[3];
        _input[0] = estudiante.puntos();
        _input[1] = equivocaciones;
        _input[2] = palabra1 + palabra2 + palabra3 + palabra4;
        palabra1 = 0;
        palabra2 = 0;
        palabra3 = 0;
        palabra4 = 0;
        switch (jugar(sistema.crispInference(_input))) {
            case 1:
                BuscarObjeto.setBounds(0, 0, 500, 400);
                lblPuntaje.setText("PUNTAJE: " + estudiante.puntos());
                BuscarObjeto.setVisible(true);
                crearRonda();
                break;
            case 2:
                HazPareja.setBounds(0, 0, 660, 395);
                lblPuntajeJuego2.setText("PUNTAJE: " + estudiante.puntos());
                HazPareja.setVisible(true);
                crearRondaOpc2();
                break;
            case 3:
                Memorizar.setBounds(0, 0, 750, 450);
                lblPuntajeJuego3.setText("PUNTAJE: " + estudiante.puntos());
                crearRondaOpc3(4);
                Memorizar.setVisible(true);
                Runnable h = new Runnable() {
                    @Override
                    public void run() {
                        visibles(false);
                        for (int i = 0; i < 3; i++) {
                            try {
                                visiblePalabra(true);
                                Thread.sleep(2000);
                                visiblePalabra(false);
                            } catch (InterruptedException ex) {}
                        }
                        visibles(true);
                    }
                };
                Thread hilo = new Thread(h);
                hilo.start();
                break;
        }
    }

    private void visibles(boolean visible) {
        jCheckBoxJuego3Pal1.setVisible(visible);
        jTextFieldJuego3Pal1.setVisible(visible);
        jCheckBoxJuego3Pal2.setVisible(visible);
        jTextFieldJuego3Pal2.setVisible(visible);
        jCheckBoxJuego3Pal3.setVisible(visible);
        jTextFieldJuego3Pal3.setVisible(visible);
        jCheckBoxJuego3Pal4.setVisible(visible);
        jTextFieldJuego3Pal4.setVisible(visible);
        jCheckBoxJuego3Pal5.setVisible(visible);
        jTextFieldJuego3Pal5.setVisible(visible);
        jCheckBoxJuego3Pal6.setVisible(visible);
        jTextFieldJuego3Pal6.setVisible(visible);
        jCheckBoxJuego3Pal7.setVisible(visible);
        jTextFieldJuego3Pal7.setVisible(visible);
        jCheckBoxJuego3Pal8.setVisible(visible);
        jTextFieldJuego3Pal8.setVisible(visible);
        jCheckBoxJuego3Pal9.setVisible(false);
        jTextFieldJuego3Pal9.setVisible(false);
        jCheckBoxJuego3Pal10.setVisible(false);
        jTextFieldJuego3Pal10.setVisible(false);
    }
}
